# Build stage
FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -o /hello .

# Final stage
FROM scratch
COPY --from=builder /hello /hello
ENTRYPOINT ["/hello"]
